# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contrast.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(595, 297)
        Widget.setStyleSheet("background-color:#3c3f41;\n"
"color: #f2f2f2")
        self.layoutWidget = QtWidgets.QWidget(Widget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 200, 500, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.ok_pushButton.setObjectName("ok_pushButton")
        self.horizontalLayout.addWidget(self.ok_pushButton)
        spacerItem = QtWidgets.QSpacerItem(218, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.apply_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.horizontalLayout.addWidget(self.apply_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(218, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.reset_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.horizontalLayout.addWidget(self.reset_pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(Widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 40, 401, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.window_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.window_spinBox.setObjectName("window_spinBox")
        self.gridLayout.addWidget(self.window_spinBox, 1, 1, 1, 1)
        self.level_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.level_spinBox.setObjectName("level_spinBox")
        self.gridLayout.addWidget(self.level_spinBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)
        Widget.setTabOrder(self.level_spinBox, self.window_spinBox)
        Widget.setTabOrder(self.window_spinBox, self.ok_pushButton)
        Widget.setTabOrder(self.ok_pushButton, self.apply_pushButton)
        Widget.setTabOrder(self.apply_pushButton, self.reset_pushButton)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.ok_pushButton.setText(_translate("Widget", "OK"))
        self.apply_pushButton.setText(_translate("Widget", "Apply"))
        self.reset_pushButton.setText(_translate("Widget", "Reset"))
        self.label_2.setText(_translate("Widget", "Window: "))
        self.label.setText(_translate("Widget", "Level: "))
