# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_img2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setMinimumSize(QtCore.QSize(600, 500))
        Form.setMaximumSize(QtCore.QSize(600, 500))
        Form.setStyleSheet("background-color:#3c3f41;\n"
"color: #f2f2f2;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.img1 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img1.sizePolicy().hasHeightForWidth())
        self.img1.setSizePolicy(sizePolicy)
        self.img1.setMinimumSize(QtCore.QSize(580, 0))
        self.img1.setMaximumSize(QtCore.QSize(580, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(28)
        self.img1.setFont(font)
        self.img1.setStyleSheet("QLabel{\n"
"    border-radius: 1px;\n"
"    color: rgb(0, 120, 215);\n"
"    border: 2px solid rgb(0, 120, 255);\n"
"}\n"
"")
        self.img1.setObjectName("img1")
        self.horizontalLayout_2.addWidget(self.img1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("border-radius: 1px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_last = QtWidgets.QPushButton(self.frame_2)
        self.btn_last.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_last.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        self.btn_last.setFont(font)
        self.btn_last.setStyleSheet("QPushButton{\n"
"    border-radius: 50px;\n"
"    background-color: rgba(0, 120, 215, 180);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 120, 215, 255);\n"
"}")
        self.btn_last.setObjectName("btn_last")
        self.horizontalLayout_8.addWidget(self.btn_last)
        self.btn_play = QtWidgets.QPushButton(self.frame_2)
        self.btn_play.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_play.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        self.btn_play.setFont(font)
        self.btn_play.setStyleSheet("QPushButton{\n"
"    border-radius: 50px;\n"
"    background-color: rgba(0, 120, 215, 180);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 120, 215, 255);\n"
"}")
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_8.addWidget(self.btn_play)
        self.btn_next = QtWidgets.QPushButton(self.frame_2)
        self.btn_next.setMinimumSize(QtCore.QSize(100, 100))
        self.btn_next.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(18)
        self.btn_next.setFont(font)
        self.btn_next.setStyleSheet("QPushButton{\n"
"    border-radius: 50px;\n"
"    background-color: rgba(0, 120, 215, 180);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 120, 215, 255);\n"
"}")
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_8.addWidget(self.btn_next)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "微创手术器械识别与分割"))
        self.img1.setText(_translate("Form", "       加载中"))
        self.btn_last.setText(_translate("Form", "上一帧"))
        self.btn_play.setText(_translate("Form", "暂停"))
        self.btn_next.setText(_translate("Form", "下一帧"))
